
-- 쿠콘통해서 문의시
-- 카드번호(cardno), 승인번호(apprno), 승인일자(apprdate) 중요

-- 사용내역 관리 > 법인카드 사용내역
SELECT
	TB2.PNO
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.CLASS            END AS CLASS
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.CLASS_NM         END AS CLASS_NM
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.CARDNO           END AS CARDNO
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.CARDNO_FORMAT    END AS CARDNO_FORMAT
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.APPRDATE         END AS APPRDATE
	, TB2.APPRTOT || '' AS APPRTOT
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.MERCHNAME        END AS MERCHNAME
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.MCCNAME          END AS MCCNAME
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.MCCCODE          END AS MCCCODE
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.MERCHBIZNO       END AS MERCHBIZNO
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.MERCHNO          END AS MERCHNO
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.MERCHADDR        END AS MERCHADDR
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.USER_NM          END AS USER_NM
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.APPRNO           END AS APPRNO
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.PURCHDATE        END AS PURCHDATE
	, TB2.PURCHTOT || '' AS PURCHTOT
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.BUCODE           END AS BUCODE
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.BUNAME           END AS BUNAME
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.TRACQ            END AS TRACQ
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE F_GET_CARD_BRAND(TB2.CARDNO)  END AS LOCALBRAND
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.COOPNAME         END AS COOPNAME
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.SETTDAY          END AS SETTDAY
	, TB2.APPRAMT1 || '' AS APPRAMT1
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE '' || TB2.VAT1         END AS VAT1
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE '' || TB2.TIPS         END AS TIPS
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.VATYN            END AS VATYN
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.INDVDL_USE_YN    END AS INDVDL_USE_YN
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.REGBUNAME        END AS REGBUNAME
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.REGUSERNAME      END AS REGUSERNAME
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.REG_USER_DEPT_NM END AS REG_USER_DEPT_NM
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.DEPST_ID         END AS DEPST_ID
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.DEPST_NM         END AS DEPST_NM
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.DEPT_CHNG_YN     END AS DEPT_CHNG_YN
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.USER_CHNG_YN     END AS USER_CHNG_YN
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE '' || TB2.SEQ              END AS SEQ
	, TB2.GINFO
FROM(
	SELECT
		TB.PNO
		, MAX(TB.CLASS           ) AS CLASS
		, MAX(TB.CLASS_NM        ) AS CLASS_NM
		, MAX(TB.CARDNO          ) AS CARDNO
		, MAX(TB.CARDNO_FORMAT   ) AS CARDNO_FORMAT
		, REPLACE(MAX(TB.APPRDATE        ), '-' , '') AS APPRDATE
		, SUM(TB.APPRTOT         ) AS APPRTOT
		, MAX(TB.MERCHNAME       ) AS MERCHNAME
		, MAX(TB.MCCNAME         ) AS MCCNAME
		, MAX(TB.MCCCODE         ) AS MCCCODE
		, MAX(TB.MERCHBIZNO      ) AS MERCHBIZNO
		, MAX(TB.MERCHNO         ) AS MERCHNO
		, MAX(TB.MERCHADDR       ) AS MERCHADDR
		, MAX(TB.USER_NM         ) AS USER_NM
		, MAX(TB.APPRNO          ) AS APPRNO
		, MAX(TB.PURCHDATE       ) AS PURCHDATE
		, SUM(TB.PURCHTOT        ) AS PURCHTOT
		, MAX(TB.BUCODE          ) AS BUCODE
		, MAX(TB.BUNAME          ) AS BUNAME
		, MAX(TB.TRACQ           ) AS TRACQ
		, MAX(TB.COOPNAME        ) AS COOPNAME
		, MAX(TB.SETTDAY         ) AS SETTDAY
		, SUM(TB.APPRAMT1        ) AS APPRAMT1
		, MAX(TB.VAT1            ) AS VAT1
		, MAX(TB.TIPS            ) AS TIPS
		, MAX(TB.VATYN           ) AS VATYN
		, MAX(TB.INDVDL_USE_YN   ) AS INDVDL_USE_YN
		, MAX(TB.REGBUNAME       ) AS REGBUNAME
		, MAX(TB.REGUSERNAME     ) AS REGUSERNAME
		, MAX(TB.REG_USER_DEPT_NM) AS REG_USER_DEPT_NM
		, MAX(TB.DEPST_ID        ) AS DEPST_ID
		, MAX(TB.DEPST_NM        ) AS DEPST_NM
		, MAX(TB.DEPT_CHNG_YN    ) AS DEPT_CHNG_YN
		, MAX(TB.USER_CHNG_YN    ) AS USER_CHNG_YN
		, MAX(TB.SEQ             ) AS SEQ
		, GROUPING(TB.PNO) AS GINFO
	FROM (
		SELECT
			ROWNUM AS PNO
			, T.*
		FROM (
			SELECT
				   A.CLASS
				 , CASE WHEN A.CLASS = 'A' THEN CASE WHEN I.CLASS = 'A' OR I.CLASS IS NULL THEN '정상' ELSE '매입취소' END ELSE '승인취소' END AS CLASS_NM
				 , A.CARDNO
				 , F_CARDNUMBER_FORMAT(A.CARDNO) AS CARDNO_FORMAT
				 , CASE WHEN I.CARDNO IS NULL THEN A.TRANSDATE ELSE I.APPRDATE END APPRDATE /* 승인일 */
				 , CASE WHEN A.CLASS = 'A' THEN CASE WHEN I.CLASS = 'A' OR I.CLASS IS NULL THEN '' ELSE '-' END ELSE '-' END || CASE WHEN I.CARDNO IS NULL THEN A.APPRTOT ELSE DECODE(I.ABROAD, 'B', I.PURCHTOT, I.APPRTOT) END AS APPRTOT
				 , A.MERCHNAME
				 , A.MCCNAME
				 , A.MCCCODE
				 , A.MERCHBIZNO
				 , A.MERCHNO
				 , A.MERCHADDR1 || ' ' ||  A.MERCHADDR2 AS MERCHADDR
				 , K.USER_NM
				 , A.APPRNO
				 , I.PURCHDATE
				 , DECODE(I.CLASS, 'A',  I.PURCHTOT, 'B', -I.PURCHTOT) AS PURCHTOT /* 매입금액 */
				 /*
				 , J.DEPT_CD AS BUCODE
				 , M.DEPT_NM AS BUNAME
				 */
				 , NVL(UC.BUCODE, NVL(DC.BUCODE,J.DEPT_CD)) AS BUCODE
				 , NVL(UC.BUNAME , NVL(DC.BUNAME,NVL(M.DEPT_NM, L.CORPNAME))) AS BUNAME
				 , A.TRACQ
				 , L.COOPNAME
				 , DECODE(NVL(TRIM(REPLACE(I.SETTDATE,'-','')),0),0,NULL,
						  (SELECT  /*+INDEX (CAL UIDX_DWC_CAL_MSTR_02)*/ SDATES
							FROM DWC_CAL_MSTR CAL
							WHERE CAL.HOL_YN = 'N'
							  AND CAL.SDATES >= REPLACE(I.SETTDATE,'-','') AND ROWNUM = 1
					)) AS SETTDAY
				 , DECODE(I.ABROAD,'B',I.PURCHTOT, I.APPRAMT) AS APPRAMT1
				 , A.VAT AS VAT1
				 , A.TIPS
				 , A.VATYN
				 , A.INDVDL_USE_YN
				 , DC.REGBUNAME    /* 이전 원가부서명 */
				 , DC.REGUSERNAME  /* 원가부서 이전 등록자 성명 */
				 , (SELECT Y.DEPT_NM FROM DWC_USER_MSTR X, DWC_DEPT_MSTR Y WHERE X.USER_ID = DC.REGUSERID AND X.DEPT_CD = Y.DEPT_CD)
						AS REG_USER_DEPT_NM  /* 원가부서 이전 등록자 부서명 */
				 , UC.DEPST_ID AS DEPST_ID
				 , (SELECT USER_NM FROM DWC_USER_MSTR WHERE USER_ID = UC.DEPST_ID) AS DEPST_NM
				 , CASE WHEN DC.CARDNO IS NULL THEN 'N' ELSE 'Y' END DEPT_CHNG_YN
				 , CASE WHEN UC.CARDNO IS NULL THEN 'N' ELSE 'Y' END USER_CHNG_YN
				 , A.SEQ
			FROM CATS_TMP_APPROVAL A
				 , CATS_TMP_ACQUIRE I
				 , CATS_RTUN_HIST J
				 , DWC_USER_MSTR K
				 , CATS_TMP_CARDINFO L
				 , DWC_DEPT_MSTR M
				 , CATS_ITNC_DEPT_CHNG_HIST DC
				 , CATS_ITNC_USER_CHNG_HIST UC
			WHERE 1 = 1
			   AND A.CARDNO  = I.CARDNO(+)
			   AND A.APPRNO  = I.APPRNO(+)
			   AND A.TRANSDATE = I.APPRDATE(+)
			   AND A.CARDNO  = DC.CARDNO(+)
			   AND A.APPRNO  = DC.APPRNO(+)
			   AND DC.CNCL_YN(+)      = 'N'
			   AND A.CARDNO  = UC.CARDNO(+)
			   AND A.APPRNO  = UC.APPRNO(+)
			   AND A.CARDNO  = L.CARDNO
			   AND A.CARDNO  = J.CARDNO(+)
			   AND J.CARD_USE_STCD(+) = '1'
			   AND J.MNGR_ID = K.USER_ID(+)
			   AND J.DEPT_CD = M.DEPT_CD(+)

			UNION ALL
			 
			-- 승인없이 매입만 있는 경우
			SELECT
				   I.CLASS
				 , CASE WHEN I.CLASS = 'A' THEN '매입' ELSE '매입취소' END AS CLASS_NM
				 , I.CARDNO
				 , F_CARDNUMBER_FORMAT(I.CARDNO) AS CARDNO_FORMAT
				 , I.APPRDATE                                   APPRDATE /* 승인일 */
				 , CASE WHEN I.CLASS = 'A' THEN '' ELSE '-' END || DECODE(I.ABROAD, 'B', I.PURCHTOT, DECODE(I.APPRTOT, 0, I.PURCHTOT)) AS APPRTOT
				 , I.MERCHNAME
				 , I.MCCNAME
				 , I.MCCCODE
				 , I.MERCHBIZNO
				 , I.MERCHNO
				 , I.MERCHADDR1 || ' ' || I.MERCHADDR2 AS MERCHADDR
				 , K.USER_NM
				 , I.APPRNO
				 , I.PURCHDATE
				 , DECODE(I.CLASS, 'A',  I.PURCHTOT, 'B', -I.PURCHTOT) AS PURCHTOT /* 매입금액 */
				 /*
				 , J.DEPT_CD AS BUCODE
				 , M.DEPT_NM AS BUNAME
				 */
				 , NVL(UC.BUCODE, NVL(DC.BUCODE,J.DEPT_CD)) AS BUCODE
				 , NVL(UC.BUNAME , NVL(DC.BUNAME,NVL(M.DEPT_NM, L.CORPNAME))) AS BUNAME
				 , I.TRACQ
				 , L.COOPNAME
				 , DECODE(NVL(TRIM(REPLACE(I.SETTDATE,'-','')),0),0,NULL,
						  (SELECT  /*+INDEX (CAL UIDX_DWC_CAL_MSTR_02)*/ SDATES
							FROM DWC_CAL_MSTR CAL
							WHERE CAL.HOL_YN = 'N'
							   AND CAL.SDATES >= REPLACE(I.SETTDATE, '-', '') AND ROWNUM = 1
						  )) AS SETTDAY
				 , DECODE(I.ABROAD,'B',I.PURCHTOT, I.APPRAMT) AS APPRAMT1
				 , I.VAT AS VAT1
				 , I.TIPS
				 , I.VATYN
				 , '' INDVDL_USE_YN
				 , DC.REGBUNAME    /* 이전 원가부서명 */
				 , DC.REGUSERNAME  /* 원가부서 이전 등록자 성명 */
				 , (SELECT Y.DEPT_NM FROM DWC_USER_MSTR X, DWC_DEPT_MSTR Y WHERE X.USER_ID = DC.REGUSERID AND X.DEPT_CD = Y.DEPT_CD)
						AS REG_USER_DEPT_NM  /* 원가부서 이전 등록자 부서명 */
				 , UC.DEPST_ID AS DEPST_ID
				 , (SELECT USER_NM FROM DWC_USER_MSTR WHERE USER_ID = UC.DEPST_ID) AS DEPST_NM
				 , CASE WHEN DC.CARDNO IS NULL THEN 'N' ELSE 'Y' END DEPT_CHNG_YN
				 , CASE WHEN UC.CARDNO IS NULL THEN 'N' ELSE 'Y' END USER_CHNG_YN
				 , A.SEQ
			FROM CATS_TMP_ACQUIRE I
				 , CATS_TMP_APPROVAL A
				 , CATS_RTUN_HIST J
				 , DWC_USER_MSTR K
				 , CATS_TMP_CARDINFO L
				 , DWC_DEPT_MSTR M
				 , CATS_ITNC_DEPT_CHNG_HIST DC
				 , CATS_ITNC_USER_CHNG_HIST UC
			WHERE 1 = 1
			   AND I.CARDNO  = DC.CARDNO(+)
			   AND I.APPRNO  = DC.APPRNO(+)
			   AND DC.CNCL_YN(+)      = 'N'
			   AND I.CARDNO  = UC.CARDNO(+)
			   AND I.APPRNO  = UC.APPRNO(+)
			   AND I.CARDNO  = L.CARDNO
			   AND I.CARDNO  = J.CARDNO(+)
			   AND J.CARD_USE_STCD(+) = '1'
			   AND J.MNGR_ID = K.USER_ID(+)
			   AND J.DEPT_CD = M.DEPT_CD(+)
			   AND I.CARDNO  = A.CARDNO(+)
			   AND I.APPRNO  = A.APPRNO(+)
			   AND A.CARDNO IS NULL
			ORDER BY APPRDATE DESC, CARDNO ASC
			) T
		) TB
		WHERE 1 = 1
			AND REPLACE(TB.APPRDATE, '-', '') BETWEEN '20230705' and '20230705'
	GROUP BY ROLLUP(PNO)
	) TB2
;



-- 사용내역 관리 > 부서별 사용내역
SELECT
	ROWNUM AS PNO
	, BASE.CARDNO
	, F_CARDNUMBER_FORMAT(BASE.CARDNO) AS CARDNO_FORMAT
	, BASE.DEPT_NM
	, BASE.DEPT_CD
	, BASE.LOCALBRAND
	, BASE.USE_AMT || '' AS USE_AMT
	, BASE.PERSONUSE
	, LIM.CARDLMT || '' AS CARDLMT    /* 카드 총한도 */
	, LIM.CARDRESTLMT || '' AS CARDRESTLMT /* 카드 잔여한도 */
	, BASE.BUNAME /* 소속부서 */
FROM (
	SELECT
		X.CARDNO as CARDNO
		, Y.DEPT_NM
		, Y.DEPT_CD
		, F_GET_CARD_BRAND(X.CARDNO) as LOCALBRAND
		, SUM( CASE WHEN X.CLASS = 'A' THEN X.ACQUTOT ELSE -X.ACQUTOT END) as USE_AMT
		, SUM(NVL(X.PERSON1,0)) as PERSONUSE
		, MAX(X.BUCODE) AS BUCODE /* 원가소속부서코드 */
		, MAX(NVL(X.BUNAME, NVL(X.POSTNAME, NVL(Y.DEPT_NM, X.CORPNAME)))) AS BUNAME/* 소속부서 */
	FROM (
		SELECT
			A.*
			, NVL(C.BUCODE,B.DEPT_CD) as BUSER_CD
			, CASE WHEN D.INDVDL_USE_YN = 'Y' THEN 1
			   END as  PERSON1
			, C.BUCODE AS BUCODE /* 원가소속부서코드 */
			, C.BUNAME AS BUNAME /* 원가소속부서명 */
			, E.CORPNAME /* 고객명 */
			, E.POSTCODE /* 소속부서코드 */
			, E.POSTNAME /* 소속부서 */
		FROM CATS_TMP_ACQUIRE A
			, CATS_RTUN_HIST B
			, CATS_ITNC_DEPT_CHNG_HIST C
			, CATS_TMP_APPROVAL D
			, CATS_TMP_CARDINFO E
		WHERE 1 = 1
			AND A.APPRNO = D.APPRNO
			AND A.CARDNO = E.CARDNO
			AND REPLACE(A.APPRDATE,'-','') BETWEEN '20230705' and '20230705'
			AND A.CARDNO = B.CARDNO(+)
			AND B.CARD_USE_STCD(+) = '1'
			AND A.CARDNO = C.CARDNO(+)
			AND A.APPRNO = C.APPRNO(+)
			AND C.CNCL_YN(+)       = 'N'
		) X
		, (SELECT DEPT_CD,DEPT_NM , DEPT_CD_UP FROM DWC_DEPT_MSTR
		   WHERE USE_YN = 'Y'
		   ) Y
		WHERE X.BUSER_CD = Y.DEPT_CD(+)
		GROUP BY X.TRACQ , Y.DEPT_NM , X.CARDNO , Y.DEPT_CD
		HAVING Y.DEPT_CD IS NOT NULL
	) BASE
	, CATS_TMP_CARDLIMIT LIM
WHERE BASE.CARDNO  = LIM.CARDNO
ORDER BY BASE.DEPT_NM, BASE.CARDNO
;



-- 청구내역 관리 > 청구서
SELECT
	TB2.PNO
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.DEPT_CD          END AS DEPT_CD
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.DEPT_NM          END AS DEPT_NM
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.SETTDATE         END AS SETTDATE
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.CARDNO           END AS CARDNO
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE TB2.CARDNO_FORMAT    END AS CARDNO_FORMAT
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE '' || TB2.COUNT        END AS COUNT
	, TB2.BILTOT || '' AS BILTOT
	, CASE WHEN TB2.GINFO = 1 THEN '' ELSE '' || TB2.INDVDL_COUNT END AS INDVDL_COUNT
	, TB2.GINFO
FROM(
	SELECT
		TB.PNO
		, MAX(TB.DEPT_CD         ) AS DEPT_CD
		, MAX(TB.SETTDATE        ) AS SETTDATE
		, MAX(TB.DEPT_NM         ) AS DEPT_NM
		, MAX(TB.CARDNO          ) AS CARDNO
		, MAX(TB.CARDNO_FORMAT   ) AS CARDNO_FORMAT
		, MAX(TB.COUNT           ) AS COUNT
		, SUM(TB.BILTOT          ) AS BILTOT
		, NVL(MAX(TB.INDVDL_COUNT), 0) AS INDVDL_COUNT
		, GROUPING(TB.PNO) AS GINFO
	FROM (
		SELECT ROWNUM PNO
			, A.*
		FROM (
			SELECT
				   MAX(NVL(Z.BUCODE, R.DEPT_CD)) AS DEPT_CD
				 , MAX(NVL(Z.BUNAME, NVL(D.DEPT_NM, C.CORPNAME)))  AS DEPT_NM
				 , REPLACE(B.SETTDATE,'-','') AS SETTDATE
				 , B.CARDNO
				 , F_CARDNUMBER_FORMAT(B.CARDNO) AS CARDNO_FORMAT
				 , COUNT(B.CARDNO) AS COUNT
				 , SUM(DECODE(B.CLASS,'B','-'||B.BILTOT,B.BILTOT)) AS BILTOT
				 , SUM(DECODE(E.INDVDL_USE_YN,'Y',1,0)) AS INDVDL_COUNT
			   --  ,(SELECT /*+ INDEX(DWC_CAL_MSTR UIDX_DWC_CAL_MSTR_01) */  SDATES AS SDATES FROM DWC_CAL_MSTR WHERE SDATES >= REPLACE(B.SETTDATE,'-','') AND  HOL_YN = 'N' AND ROWNUM = 1) AS NEW_SETTDATE
			FROM CATS_TMP_BILL     B
				 , CATS_TMP_CARDINFO C
				 , DWC_DEPT_MSTR     D
				 , CATS_TMP_APPROVAL E
				 , CATS_RTUN_HIST    R
				 , (
					SELECT /*+ INDEX(DWC_CAL_MSTR UIDX_DWC_CAL_MSTR_01) */
						 Y.SDATES AS SDATES
						 , (SELECT /*+ INDEX(X UIDX_DWC_CAL_MSTR_01) */  SDATES
							  FROM DWC_CAL_MSTR X WHERE X.SDATES >= Y.SDATES AND  X.HOL_YN = 'N' AND ROWNUM = 1) AS WDATES
					FROM DWC_CAL_MSTR Y
					WHERE SDATES BETWEEN TO_CHAR(TO_DATE('20230707', 'YYYYMMDD') - 10 , 'YYYYMMDD') AND TO_CHAR(TO_DATE('20230707', 'YYYYMMDD') + 10, 'YYYYMMDD')
				   ) Y
				 , CATS_ITNC_DEPT_CHNG_HIST Z
			WHERE B.CARDNO   = C.CARDNO(+)
				AND B.CARDNO   = R.CARDNO(+)
				AND R.DEPT_CD  = D.DEPT_CD(+)
				AND B.APPRNO   = E.APPRNO(+)
				AND B.CARDNO   = E.CARDNO(+)
				AND B.CARDNO     = Z.CARDNO(+)
				AND B.APPRNO     = Z.APPRNO(+)
				AND R.CARD_USE_STCD(+) = '1'
				AND REPLACE(B.SETTDATE,'-','') = Y.SDATES
				AND Y.WDATES = '20230712'
			GROUP BY R.DEPT_CD, D.DEPT_NM, B.CARDNO, B.SETTDATE
			ORDER BY D.DEPT_NM, B.CARDNO, B.SETTDATE
			) A
		) TB
		WHERE 1 = 1
		GROUP BY ROLLUP(PNO)
	) TB2
;



-- 청구내역 관리 > 개인 사용분 입금확인
-- 카드사용목록
SELECT ROWNUM PNO, A.*
FROM (
	SELECT
		   DWC_CRYPT.DECRYPT(A.ACCT_NO) AS ACCT_NO
		 , FN_ACCT_FORMAT(A.BANK_CD, DWC_CRYPT.DECRYPT(A.ACCT_NO)) AS ACCT_NO_FORMAT
		 , A.DEP_NM                                                 /* 입금인성명 */
		 , DECODE(A.INOUT_GUBUN, '1', 0, '2', A.TX_AMT) AS MNRC_AMT /* 입금금액 */
		 , A.ACCT_TXDAY                                             /* 거래일자 */
	FROM FN_ACCT_HIS$ A
		 , FN_ACCT$ B
	WHERE A.ACCT_NO = B.ACCT_NO
	   AND B.CPR_CARD_SETLE_ACCT_YN = 'Y'
	ORDER BY A.ACCT_TXDAY DESC, A.ACCT_NO
	) A
WHERE 1 = 1
	AND A.ACCT_TXDAY BETWEEN '20230101' AND '20230330'
;

-- 입금목록
SELECT ROWNUM PNO, A.*
FROM (
	SELECT
		   A.SEQ
		 , A.CARDNO
		 , F_CARDNUMBER_FORMAT(A.CARDNO)    AS CARDNO_FORMAT
		 , REPLACE(A.TRANSDATE, '-', '')    AS TRDATE               /* 승인일자 */
		 , DECODE(B.CLASS,'B','-'||A.APPRTOT, A.APPRTOT) AS APPRTOT /* 승인금액 */
		 , A.MERCHNAME                                              /* 가맹점 */
		 , U1.USER_NM AS MNGR_NM                                    /* 담당자 */
		 , U2.USER_NM AS DEPST_NM                                   /* 입금자 */
		 , NVL(A.INDVDL_RCPMNY_YN, 'N')     AS INDVDL_RCPMNY_YN     /* 입금확인 */
		 , DECODE(NVL(A.INDVDL_RCPMNY_YN, 'N'), 'Y', '완료', '미완료') AS INDVDL_RCPMNY_YN_NM /* 입금확인여부 */
		 , A.APPRNO                                                 /* 승인번호 */
		 , REPLACE(C.SETTDATE, '-', '')     AS SETTDATE             /* 결제예정일 */
	FROM CATS_TMP_APPROVAL A
		 , CATS_TMP_ACQUIRE C
		 , CATS_TMP_CARDINFO B
		 , CATS_RTUN_HIST R
		 , DWC_USER_MSTR U1
		 , DWC_USER_MSTR U2
		 , CATS_ITNC_USER_CHNG_HIST H
	WHERE 1 = 1
		AND A.CARDNO           = B.CARDNO
		AND A.CARDNO           = R.CARDNO(+)
		AND A.CARDNO           = C.CARDNO(+)
		AND R.CARD_USE_STCD(+) = '1'
		AND R.MNGR_ID          = U1.USER_ID(+)
		AND A.APPRNO           = H.APPRNO(+)
		AND A.APPRNO           = C.APPRNO(+)
		AND A.CARDNO           = H.CARDNO(+)
		AND H.DEPST_ID         = U2.USER_ID(+)
		AND A.INDVDL_USE_YN    = 'Y'
		AND REPLACE(C.SETTDATE, '-', '') BETWEEN '20230101' AND '20230330'
	) A
WHERE 1 = 1
ORDER BY A.TRDATE DESC, A.CARDNO
;



-- 카드관리 > 카드정보 조회
SELECT
	ROWNUM AS PNO
	, E.CARDNO                  /* 카드번호 */
	, E.CARDNO_FORMAT           /* 카드번호_FORMAT */
	, NVL(D.DEPT_NM,E.CORPNAME) AS DEPT_NM /* 부서명 */
	, E.DEPT_CD                 /* 부서코드 */
	, E.MNGR_ID                 /* 담당자아이디 */
	, U.USER_NM  AS MNGR_NM     /* 담당자명 */
	, E.COOPNAME                /* 카드명칭 */
	, E.CORPNAME                /* 발급명의 */
	, E.TRACQ                   /* 카드사   */
	, E.SETTDAY||'일' AS SETTDAY/* 결제일   */
	, E.MEMBADDR1               /* 청구지주소 */
	, E.NOTICETYPE              /* 상태코드 */
	, E.NOTICETYPE_TEXT         /* 상태명 */
	, E.VALIDITY                /* 유효기간 */
	, E.LOCALBRAND              /* 카드사 */
	, E.CARDLMT                 /*카드한도*/
FROM (
	SELECT
		  D.CARDNO
		, F_CARDNUMBER_FORMAT(D.CARDNO) AS CARDNO_FORMAT
		, R.DEPT_CD
		, R.MNGR_ID
		, D.COOPNAME
		, D.CORPNAME
		, D.TRACQ
		, D.SETTDAY
		, D.MEMBADDR1
		, D.NOTICETYPE
		, DECODE(D.NOTICETYPE, 'A','정상','B','정상','D','정상','O','정상','C','해지','E','일시정지') AS NOTICETYPE_TEXT
		, D.VALIDITY
		, DECODE(D.LOCALBRAND, 'B','농협BC', 'D','삼성', 'K', '국민', 'S','신한', 'H','현대', 'E','외환', 'N','농협', 'W','우리', 'F','수협') AS LOCALBRAND
		, E.CARDLMT
	FROM CATS_TMP_CARDINFO D
		, CATS_TMP_CARDLIMIT E
		, CATS_RTUN_HIST R
	WHERE D.CARDNO=E.CARDNO(+)
		AND D.CARDNO=R.CARDNO(+)
		AND R.CARD_USE_STCD(+) = '1'
	) E
	 , DWC_USER_MSTR U
	 , DWC_DEPT_MSTR D
WHERE 1=1                 /* DYNAMIC 쿼리 위해서 사용 */
	AND E.MNGR_ID = U.USER_ID(+)
	AND E.DEPT_CD = D.DEPT_CD(+)
	AND E.NOTICETYPE IN ('A','B','D','O')
ORDER BY E.CARDNO
;



-- 카드관리 > 카드정보 조회 > 상세조회
SELECT
	F_CARDNUMBER_FORMAT(A.CARDNO) AS CARDNO_FORMAT /* 카드번호*/
	, U.USER_NM   /* 사용자*/
	, A.KORNAME   /* 발급명의(한굴)*/
	, A.ENGNAME   /* 발급명의(영문)*/
	, A.REGISTNO  /* 주미등록번호*/
	, D.DEPT_NM   /* 부서명 */
	, A.CORPBIZNO /* 사업자번호 */
	, A.CORPNAME  /* 업체명 */
	, DECODE(A.CARDBRAND, '4','VISA', '5','MASTER', '0','AMEX', '1','LOCAL', '2','다이너스카드', '3','JCB', '6','은련카드') AS CARDBRAND /* 카드구분 */
	, DECODE(A.CARDTYPE3,'A','법인카드', 'B','주유전용', 'C','항공전용', 'D','복지전용', 'E','연구비전용', 'F','지정자카드', 'T','TaxBill카드', 'K','KT카드')AS CARDTYPE3 /* 카드상품 */
	, CASE WHEN A.LOCALBRAND in ('N','B')
		THEN DECODE(A.CARDTYPE4, '1','플러스','2','일반','3','우량','4','골드','5','플래티넘','6','E-플래티넘','7','다이아몬드','8','인피니트')
		ELSE DECODE(A.CARDTYPE4, 'A','CLASSIC', 'B','GOLD', 'C','플래티넘', 'D','기타')
		 END AS CARDTYPE4  /* 카드등급 */
	, A.VALIDITY  /* 유효기간 */
	, DECODE(A.NOTICETYPE, 'A','정상','B','정상','D','정상','O','정상','C','해지','E','일시정지') as NOTICETYPE_TEXT /* 카드상태 */
	, A.SETTDAY   /* 결재일 */
	, B.BANK_NM AS SETTBANKNM /* 은행명 */
	, FN_ACCT_FORMAT(A.SETTBANKCODE, A.SETTACCTNO) AS ACCT_NO_FORMAT /* 결제계좌번호 포맷 */
	, A.COOPNAME  /* 제휴카드명(카드상품) */
	, A.ISSUEDATE /* 발급일 */
	, A.TMNTDATE  /* 해지일 */
	, A.MEMBZIPCODE /* 청구지 우편번호 */
	, A.MEMBADDR1   /* 청구지 주소-1 */
	, A.MEMBADDR2   /* 청구지 주소-2 */
	, E.CARDLMT     /* 총한도 */
	, E.CARDRESTLMT /* 잔여한도 */
	, E.CORPLMT     /* 업체총한도 */
	, E.CORPRESTLMT /* 업체잔여한도 */
	, TO_CHAR(TO_NUMBER(E.CARDLMT) - TO_NUMBER(E.CARDRESTLMT) ) AS CARDUSEDAMT    /* 사용금액 */
FROM CATS_TMP_CARDINFO  A
	, BA_BANK            B
	, CATS_TMP_CARDLIMIT E
	, CATS_RTUN_HIST     R
	, DWC_USER_MSTR      U
	, DWC_DEPT_MSTR      D
WHERE A.CARDNO  = R.CARDNO(+)
	AND A.CARDNO  = E.CARDNO(+)
	AND R.CARD_USE_STCD(+) = '1'
	AND R.USER_ID = U.USER_ID(+)
	AND R.DEPT_CD = D.DEPT_CD(+)
	AND ('1' || LPAD(A.SETTBANKCODE, 7, '0')) = B.BANK_CD(+)
	AND A.CARDNO  = '4140114420820112'
;



-- 카드관리 > 부서별 카드조회
SELECT DEPT_PNO AS PNO
	 , LEVEL AS DEPT_LEVEL
	 , LPAD('   ', 3*LEVEL)||DEPT_NM AS LAYER_DEPT_NM
	 , '['||DEPT_CD||']    '||DEPT_NM AS DEPT_INFO
	 , DEPT_CD AS ID
	 , CARDCNT
	 , DEPT_NM
	 , DEPT_CD_UP AS PID
	 , GRP_YN
FROM (
	    SELECT DISTINCT (DEPT_PNO)
			, DEPT_CD
			, (SELECT COUNT(*)
				 FROM CATS_RTUN_HIST A
					, (SELECT DEPT_CD
						FROM DWC_DEPT_MSTR
						WHERE 1 = 1
							AND USE_YN = 'Y'
					    CONNECT BY PRIOR DEPT_CD = DEPT_CD_UP START WITH DEPT_CD = AA.DEPT_CD
					) B
				WHERE 1 = 1
					AND A.CARD_USE_STCD = '1'
					AND A.DEPT_CD = B.DEPT_CD) AS CARDCNT
			, DEPT_NM
			, DEPT_CD_UP
			, GRP_YN
		FROM DWC_DEPT_MSTR AA
		WHERE 1 = 1
		   AND USE_YN = 'Y'
	) CONNECT BY PRIOR DEPT_CD = DEPT_CD_UP START WITH DEPT_CD_UP IS NULL
;


-- 카드관리 > 부서별 카드조회 > 소속카드
SELECT
	   D.CARDNO
	 , F_CARDNUMBER_FORMAT(D.CARDNO) AS CARDNO_FORMAT
	 , CD.CMM_CD_NM AS LOCALBRAND
	 , CASE WHEN C.CARD_USE_STCD='1' THEN '활동' ELSE '비활동' END AS CARD_USE_STCD
	 , B.DEPT_NM
	 , C.START_DT
	 , C.MNGR_ID
	 , E.USER_NM AS MNGR_NM
	 , Y.DEPT_NM AS MNGR_DEPT_NM
FROM
	   DWC_DEPT_MSTR B
	 , CATS_RTUN_HIST C
	 , CATS_TMP_CARDINFO D
	 , DWC_USER_MSTR E
	 , DWC_CMM_CODE CD
	 , DWC_USER_MSTR X
	 , DWC_DEPT_MSTR Y
WHERE 1 = 1
	AND D.LOCALBRAND       = CD.CMM_CD(+)
	AND CD.GRP_CD(+)       = 'KT006'
	AND C.DEPT_CD          = B.DEPT_CD(+)
	AND C.CARDNO(+)        = D.CARDNO
	AND C.CARD_USE_STCD(+) = '1'
	AND C.MNGR_ID          = E.USER_ID(+)
	AND C.MNGR_ID          = X.USER_ID(+)
	AND X.DEPT_CD          = Y.DEPT_CD(+)
	AND B.DEPT_CD IN (
					SELECT DISTINCT(DEPT_CD) AS DEPT_CD
					FROM
						( SELECT A.DEPT_CD AS TEST
							, B.DEPT_CD AS DEPT_CD
						FROM DWC_DEPT_MSTR A
							, DWC_DEPT_MSTR B
						WHERE A.DEPT_CD = B.DEPT_CD_UP
							AND A.USE_YN = 'Y'
							AND B.USE_YN = 'Y'
						CONNECT BY PRIOR A.DEPT_CD = A.DEPT_CD_UP
							START WITH A.DEPT_CD = 'AA0002'
						ORDER SIBLINGS BY A.DEPT_CD )
						
						UNION ALL
						
					    SELECT DEPT_CD
						FROM DWC_DEPT_MSTR
						WHERE DEPT_CD = 'AA0002'
							AND USE_YN = 'Y'
					)
;



-- 카드관리 > 법인카드 권한조회





























